import './globals.css'
import Header from '../Components/Header'
import Footer from '../Components/Footer'
import { Roboto } from 'next/font/google'
import Link from 'next/link'
import { StoreProvider } from './store/StoreProvider'
 
const roboto = Roboto({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['cyrillic', 'latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
          <Header />
          <StoreProvider>{children}</StoreProvider>
          <Footer />
      </body>
    </html>
  )
}
